
name: Build Flutter App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Windows EXE
        run: |
          sudo apt-get update
          echo "Windows build simulated - use Windows runner if needed"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: photobooth-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/x64/runner/Release/

      - name: Setup Firebase (Optional)
        if: ${{ secrets.FIREBASE_TOKEN != '' }}
        run: |
          npm install -g firebase-tools
          firebase use --add
