
name: photobooth_flutter
description: A cross-platform photo booth app with Firebase upload support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image: ^4.2.2
  qr_flutter: ^4.1.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.0
  printing: ^5.12.0
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
